import { useState } from 'react'
import { createFileRoute, Link, useParams } from '@tanstack/react-router'
import { useInvestigation } from '@/hooks/use-investigations'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { TerminalPanel } from '@/components/terminal/TerminalPanel'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Button } from '@/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { ArrowLeft, Activity, Server, Clock, AlertTriangle, Code, Copy, Check } from 'lucide-react'
import { toast } from 'sonner'

export const Route = createFileRoute('/_authenticated/investigations/$id')({
  component: InvestigationDetailsPage,
})

function InvestigationDetailsPage() {
  const { id } = useParams({ from: '/_authenticated/investigations/$id' })
  const { data: inv, isLoading, isError } = useInvestigation(id)
  const queryClient = useQueryClient()
  const [generatedScript, setGeneratedScript] = useState<{ script: string; language: string } | null>(null)
  const [copied, setCopied] = useState(false)

  const generateScript = useMutation({
    mutationFn: async () => {
      const resp = await api.post(`/investigations/${id}/generate-script`)
      return resp.data
    },
    onSuccess: (data) => {
      setGeneratedScript({ script: data.script, language: data.language })
      queryClient.invalidateQueries({ queryKey: ['investigations', id] })
      toast.success('Remediation script generated by Bedrock')
    },
    onError: () => toast.error('Script generation failed')
  })

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    toast.success('Copied to clipboard')
    setTimeout(() => setCopied(false), 2000)
  }

  const getPriorityBadgeClass = (priority: string) => {
    switch (priority.toLowerCase()) {
      case 'high': return 'text-[#FF5555] border-[#FF5555]/20 bg-[#FF5555]/5'
      case 'medium': return 'text-[#FFB020] border-[#FFB020]/20 bg-[#FFB020]/5'
      case 'low': return 'text-[#58A6FF] border-[#58A6FF]/20 bg-[#58A6FF]/5'
      default: return 'text-muted-foreground border-border bg-[#161616]'
    }
  }

  const getStatusClass = (status: string) => {
    return status.toLowerCase() === 'resolved'
      ? 'text-[#00FF88] border-[#00FF88]/20 bg-[#00FF88]/5'
      : 'text-[#FFB020] border-[#FFB020]/20 bg-[#FFB020]/5'
  }

  if (isLoading) {
    return (
      <div className='flex flex-col items-center justify-center min-h-[400px] font-mono text-xs text-muted-foreground space-y-3'>
        <Activity className='h-8 w-8 text-primary animate-spin' />
        <span>Running incident telemetry diagnosis...</span>
      </div>
    )
  }

  if (isError || !inv) {
    return (
      <div className='max-w-md mx-auto py-12 font-mono text-xs'>
        <Alert variant='destructive' className='rounded-none bg-[#FF5555]/5 border-[#FF5555]/30 text-[#FF5555]'>
          <AlertTriangle className='h-4 w-4 text-[#FF5555]' />
          <AlertTitle className='font-bold uppercase tracking-wider'>Diagnostic Error</AlertTitle>
          <AlertDescription className='text-[10px] mt-1'>Could not fetch investigation details.</AlertDescription>
          <div className='mt-4'>
            <Button asChild size='sm' className='h-6 text-[10px] border-[#FF5555]/30 bg-[#FF5555]/10 text-[#FF5555] hover:bg-[#FF5555]/20 rounded-none'>
              <Link to='/investigations'>Back to Registry</Link>
            </Button>
          </div>
        </Alert>
      </div>
    )
  }

  return (
    <div className='space-y-6 font-mono text-xs text-foreground'>
      {/* Navigation */}
      <div className='border-b border-border/60 pb-4 mb-4'>
        <Button asChild variant='ghost' size='sm' className='mb-2 h-7 text-[10px] text-muted-foreground hover:text-foreground cursor-pointer rounded-none pl-0'>
          <Link to='/investigations'><ArrowLeft className='mr-1.5 h-3.5 w-3.5' />BACK TO REGISTRY</Link>
        </Button>
        <div className='flex flex-col md:flex-row md:items-center md:justify-between gap-y-2'>
          <div>
            <div className='flex items-center space-x-3'>
              <h1 className='text-sm font-bold text-primary tracking-tight select-text'>{inv.title.toUpperCase()}</h1>
              <span className={`px-1.5 py-0.5 border text-[9px] font-bold ${getStatusClass(inv.status)}`}>{inv.status.toUpperCase()}</span>
            </div>
            <p className='text-muted-foreground text-[10px] mt-1 select-text'>ID: {inv.id}</p>
          </div>
          <button
            onClick={() => generateScript.mutate()}
            disabled={generateScript.isPending}
            className='px-3 py-1.5 border border-[#00FF88]/55 bg-[#00FF88]/10 text-[#00FF88] hover:bg-[#00FF88]/25 cursor-pointer font-bold uppercase flex items-center space-x-1.5 text-[10px] disabled:opacity-40'
          >
            <Code className={`h-3.5 w-3.5 ${generateScript.isPending ? 'animate-pulse' : ''}`} />
            <span>{generateScript.isPending ? 'GENERATING...' : 'GENERATE FIX SCRIPT'}</span>
          </button>
        </div>
      </div>

      {/* Generated Script Panel */}
      {generatedScript && (
        <TerminalPanel title={`AI-GENERATED REMEDIATION (${generatedScript.language.toUpperCase()})`} collapsible
          rightElement={
            <button onClick={() => handleCopy(generatedScript.script)}
              className='px-2 py-0.5 border border-border/60 bg-[#161616] text-muted-foreground hover:text-foreground text-[9px] flex items-center gap-1 cursor-pointer'>
              {copied ? <Check className='h-3 w-3 text-[#00FF88]' /> : <Copy className='h-3 w-3' />}
              {copied ? 'COPIED' : 'COPY'}
            </button>
          }
        >
          <pre className='text-[10px] bg-[#090909] p-3 border border-[#00FF88]/20 text-[#00FF88] overflow-x-auto whitespace-pre-wrap leading-relaxed select-text max-h-[300px] overflow-y-auto'>
            {generatedScript.script}
          </pre>
        </TerminalPanel>
      )}

      {/* Tabs */}
      <Tabs defaultValue='overview' className='space-y-4'>
        <TabsList className='w-full justify-start border-b border-border rounded-none h-9 bg-transparent p-0 space-x-1.5 overflow-x-auto no-scrollbar'>
          {['overview', 'timeline', 'root-cause', 'recommendations', 'evidence'].map((tab, i) => (
            <TabsTrigger key={tab} value={tab}
              className='rounded-none border border-transparent data-[state=active]:border-border data-[state=active]:bg-[#111111] data-[state=active]:text-primary px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider'>
              [{String(i + 1).padStart(2, '0')}. {tab.replace('-', ' ')}]
            </TabsTrigger>
          ))}
        </TabsList>

        {/* OVERVIEW */}
        <TabsContent value='overview' className='space-y-4'>
          <div className='grid gap-6 md:grid-cols-12'>
            <div className='md:col-span-8 space-y-4'>
              <TerminalPanel title='Investigation Query'>
                <div className='bg-[#090909] p-3 border border-border/40 select-text leading-relaxed text-[11px] whitespace-pre-wrap text-[#E6EDF3]'>
                  {inv.question}
                </div>
              </TerminalPanel>
              <TerminalPanel title='AI Diagnosis Summary'>
                <div className='bg-[#090909] p-3 border border-border/40 select-text leading-relaxed text-[11px] text-[#00FF88] whitespace-pre-wrap'>
                  {inv.summary || 'Pending analysis...'}
                </div>
              </TerminalPanel>
            </div>
            <div className='md:col-span-4'>
              <TerminalPanel title='Service Metadata'>
                <div className='space-y-3 text-[10px] select-text'>
                  <div className='flex items-center space-x-3 p-2 bg-[#090909] border border-border/40'>
                    <Server className='h-4 w-4 text-primary flex-shrink-0' />
                    <div>
                      <div className='font-bold text-[#E6EDF3] uppercase'>{inv.service?.name || 'NODE'}</div>
                      <div className='text-[9px] text-muted-foreground'>{inv.service?.environment?.toUpperCase()} • {inv.service?.owner}</div>
                    </div>
                  </div>
                  <div className='border-t border-border/20 pt-2 space-y-1 text-muted-foreground'>
                    <div className='flex justify-between'><span>CREATED:</span><span className='text-foreground'>{new Date(inv.created_at).toLocaleString()}</span></div>
                    <div className='flex justify-between'><span>UPDATED:</span><span className='text-foreground'>{new Date(inv.updated_at).toLocaleString()}</span></div>
                  </div>
                </div>
              </TerminalPanel>
            </div>
          </div>
        </TabsContent>

        {/* TIMELINE */}
        <TabsContent value='timeline'>
          <TerminalPanel title='Incident Timeline'>
            {inv.timeline.length === 0 ? (
              <p className='text-muted-foreground py-4'>No timeline events.</p>
            ) : (
              <div className='relative border-l border-border/60 pl-6 space-y-6 py-2 ml-4 select-text'>
                {inv.timeline.map((event) => (
                  <div key={event.id} className='relative leading-normal'>
                    <div className='absolute -left-[31px] top-1 flex h-4.5 w-4.5 items-center justify-center rounded-full border border-border bg-[#090909] text-primary'>
                      <Clock className='h-2.5 w-2.5 text-primary' />
                    </div>
                    <div>
                      <div className='flex flex-wrap items-center gap-x-2 gap-y-1'>
                        <span className='font-bold text-foreground text-[10px]'>{event.title.toUpperCase()}</span>
                        <span className='px-1 py-0.5 border border-border bg-[#161616] text-muted-foreground text-[8px]'>
                          {new Date(event.event_time).toLocaleTimeString()}
                        </span>
                      </div>
                      <p className='text-[10px] text-muted-foreground mt-1 leading-relaxed'>{event.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </TerminalPanel>
        </TabsContent>

        {/* ROOT CAUSE */}
        <TabsContent value='root-cause'>
          <TerminalPanel title='Root Cause Analysis'>
            <div className='bg-[#090909] p-4 border border-border/40 select-text leading-relaxed text-[11px] whitespace-pre-wrap text-[#00FF88]'>
              {inv.root_cause || 'Pending root cause analysis...'}
            </div>
          </TerminalPanel>
        </TabsContent>

        {/* RECOMMENDATIONS */}
        <TabsContent value='recommendations'>
          <TerminalPanel title='Remediation Recommendations'>
            {inv.recommendations.length === 0 ? (
              <p className='text-muted-foreground py-4'>No recommendations yet. Click "Generate Fix Script" above.</p>
            ) : (
              <div className='space-y-3 select-text'>
                {inv.recommendations.map((rec) => (
                  <div key={rec.id} className='border border-border/40 bg-[#090909] p-3'>
                    <div className='flex items-center gap-2 mb-2'>
                      <span className={`px-1.5 py-0.5 border text-[8px] font-bold ${getPriorityBadgeClass(rec.priority)}`}>
                        {rec.priority.toUpperCase()}
                      </span>
                      <span className='font-bold text-[10px] text-foreground'>{rec.title.toUpperCase()}</span>
                    </div>
                    {rec.description.includes('```') ? (
                      <pre className='text-[10px] bg-[#050505] p-2 border border-[#00FF88]/15 text-[#00FF88] overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[250px] overflow-y-auto'>
                        {rec.description.replace(/```\w*\n?/g, '').replace(/```/g, '')}
                      </pre>
                    ) : (
                      <p className='text-[10px] text-muted-foreground leading-relaxed'>{rec.description}</p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </TerminalPanel>
        </TabsContent>

        {/* EVIDENCE */}
        <TabsContent value='evidence'>
          <TerminalPanel title='Diagnostic Evidence'>
            {inv.evidence.length === 0 ? (
              <p className='text-muted-foreground py-4'>No evidence collected.</p>
            ) : (
              <div className='space-y-4 select-text'>
                {inv.evidence.map((item) => (
                  <div key={item.id} className='border border-border/40 bg-[#090909] p-3'>
                    <div className='flex items-center justify-between mb-2'>
                      <span className='text-[9px] text-primary font-bold uppercase'>{item.source}</span>
                      <button onClick={() => handleCopy(item.details)}
                        className='px-1.5 py-0.5 border border-border/40 text-muted-foreground hover:text-foreground text-[8px] cursor-pointer flex items-center gap-1'>
                        <Copy className='h-2.5 w-2.5' /> COPY
                      </button>
                    </div>
                    <pre className='text-[10px] bg-[#050505] p-2 border border-border/20 text-foreground overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[200px] overflow-y-auto'>
                      {item.details}
                    </pre>
                  </div>
                ))}
              </div>
            )}
          </TerminalPanel>
        </TabsContent>
      </Tabs>
    </div>
  )
}
